Move libraries from internal to pkg
GoogleCloudPlatform/artifact-registry-go-tools pull request #11
Opened 2023-07-12 18:48 UTC by Aleromerog

M ove libraries to make them public so other packages (like GCB) can depend on.

2023-09-02 23:37 UTC, yihanzhen approved these changes

2023-09-02 23:38 UTC, yihanzhen requested changes
Please update the imports here too: https://github.com/GoogleCloudPlatform/artifact-registry-go-tools/blob/main/cmd/auth/main.go#L25-L26

2023-09-05 18:29 UTC, Aleromerog commented
> Please update the imports here too: https://github.com/GoogleCloudPlatform/artifact-registry-go-tools/blob/main/cmd/auth/main.go#L25-L26

Should be good now, updated it to main file and netrc

2023-09-05 19:08 UTC, yihanzhen approved these changes

2023-09-05 19:09 UTC, merged